### PR TITLE
Initial EL (RHEL, CentOS, Fedora, Scientific Linux, Amazon Linux, etc) support

### PR DESCRIPTION
**Pull request by jethrocarr**
This change introduces support for RedHat, Fedora, CentOS, Scientific Linux,
Amazon Linux, etc. The support isn't complete, in that master/slave mode
isn't supported yet, however this is handled with a graceful error
message.

The biggest adjustment is moving all the params into a dedicated
params.pp file and adding the complete set of configuration files to the
modules.

It also fixes issue #25 as it ensures consistent behaviour regardless of
variations in package manager between different distributions.

### CODE REVIEW

**Comment by jethrocarr** [comment]
I'd like to have master/slave working for EL as well, but it's likely to be a while before I have time to attack that and figure you might like to get standalone EL support merged sooner rather than later.

I've tested with Ubuntu 14.04, Fedora 22 and CentOS 7 in standalone modes, but NOT master/slave mode, so please conduct some additional tests there to make 100% sure it wasn't impacted in any way. There should be no change to Ubuntu systems other than Puppet taking ownership of all the default Smokeping configuration files, not just the ones we tweak.

**Comment by jethrocarr** [comment]
Fedora ships with it's own Smokeping RPM, however CentOS lacks one - I tested with a copy of the Fedora one backported (available at https://repos.jethrocarr.com/) which worked fine.

**Comment by tobru** [comment]
Thanks a lot for your work. I'll give it a try soon merge your PR then for having a new module release soon.

**Comment by jethrocarr** [comment]
Thanks @tobru, let me know if you run into any issues or need any tweaks.

**Pull request merged**
