### PR TITLE
Fixed error while using slave_display_name (was ignored)

### PR DESCRIPTION
**Pull request by fetzerms**
Setting the display name using "slave_display_name" did not work here. The following fix solves this.

### CODE REVIEW

**Comment by fetzerms** [comment]
If you want to merge both, #26 & #27 i can also create a pull request from my master branch, which includes both fixes.

**Comment by tobru** [comment]
Ok, so I've merged the other one. Could you please rebase to master so that I can merge this one?

**Comment by fetzerms** [comment]
Rebased fix_display_name to master. You should be able to merge now.

**Comment by tobru** [comment]
thanks!

**Comment by fetzerms** [comment]
That was fast ;). You're welcome.

**Pull request merged**
